# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   app.session:
      class: Symfony\Component\HttpFoundation\Session\Session
      callMethod: 'start'
   cart.adapter.file:
      class: ecommarg\cart\FileAdapter
      arguments: ['e:\\']
   cart.adapter.session:
      class: ecommarg\cart\Cart
      arguments: ['@app.session']
   app.cart:
      class: ecommarg\cart\Cart
      arguments: ['@cart.adapter.file']




    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
